### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by garci66** [ms264556/Hackery#8]
deleted

**Comment by ms264556** [comment]
Thanks for your kind feedback!

Unfortunately, I won't be able to fix this issue in the short term.

Your added licences are permanent: they will persist through upgrades and factory resets.  
The 30 day support entitlement currently resets whenever it runs out, so you could just upgrade now to the latest release and live with the red support-nearly-expired banner - I have.

Some background:-

Ruckus contacted me to let me know they still sell licenses and support, and ask that I remove the licence patch from GitHub.  
I guess businesses were abusing my helpfulness and costing Ruckus money.

If the situation changes (e.g. Ruckus stop rolling over the support license, or disable existing patched licenses) then I'll release an updated patch using a different vulnerability. Otherwise, I won't be tweaking things, sorry.

**Comment by garci66** [comment]
fully understand! thanks for the work regardless.!!

**Comment by garci66** [comment]
Its also interesting to see how much unleashed code is being referenced in the scripts in the image... references to ICX managment, etc...
